version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: english-go-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: English-GO
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: english-go-api:latest
    container_name: english-go-api
    restart: always
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN_SECRET=123456
      - ACCESS_TOKEN_EXPIRES_IN=2592000
      - DB_USERNAME=admin
      - DB_PASSWORD=Admin@123
      - DB_NAME=English-GO
      - DB_HOST=database
      - DB_PORT=5432
      - AUTH_MODE=HEADER
      - AUTH_SERVER_URL=https://login.vinhuni.edu.vn
      - VINHUNI_API_URL=https://usmart.vinhuni.edu.vn
    ports:
      - "5555:5555"
    command: >
      sh -c "npm run migration:run && node dist/src/index.js"
    volumes:
      - ./:/usr/src/app

volumes:
  postgres-data:
