name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Run workflow on push to the main branch

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest
    environment: Production

    steps:
      # Step 1: Checkout the code
      - name: Checkout Main
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -f .docker/Dockerfile -t ${{ vars.DOCKER_USER }}/english-go-api:latest .

      # Step 4: Push the Docker Image to Registry
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ vars.DOCKER_USER }}/english-go-api:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    environment: Production

    steps:
      - name: Deploy on Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ vars.SERVER_USER }}/app/nodejs/english-go-api
            docker-compose pull
            docker-compose down
            docker-compose up -d
